from datetime import datetime
from pathlib import Path
from uuid import uuid4

import streamlit as st

from src.solaris_pm import process_file, write_index_dashboard, write_summary_csv

OUTPUT_DIR = Path("outputs")
UPLOAD_DIR = Path("web_uploads")
SAMPLE_REPORT = Path("sample_data") / "sample_solaris_pm_report.txt"


def get_session_id():
    if "session_id" not in st.session_state:
        st.session_state.session_id = uuid4().hex

    return st.session_state.session_id


def prepare_run_folders():
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    session_id = get_session_id()

    upload_dir = UPLOAD_DIR / session_id
    output_dir = OUTPUT_DIR / session_id / timestamp

    upload_dir.mkdir(parents=True, exist_ok=True)
    output_dir.mkdir(parents=True, exist_ok=True)

    return upload_dir, output_dir, timestamp


def download_file(file_path, label, mime_type):
    if file_path.exists():
        st.download_button(
            label=label,
            data=file_path.read_bytes(),
            file_name=file_path.name,
            mime=mime_type,
            use_container_width=True,
        )
    else:
        st.warning(f"File not found: {file_path.name}")


def render_result(result):
    row = result["row"]
    input_name = result["input_name"]
    run_output_dir = Path(result["output_dir"])

    checklist_path = run_output_dir / f"{input_name}_checklist.md"
    findings_path = run_output_dir / f"{input_name}_findings.json"
    explanation_path = run_output_dir / f"{input_name}_explanation.md"
    dashboard_path = run_output_dir / f"{input_name}_dashboard.html"
    pdf_path = run_output_dir / f"{input_name}_pm_report.pdf"
    summary_csv_path = run_output_dir / "summary.csv"
    index_dashboard_path = run_output_dir / "index.html"

    hostname = row.get("Hostname", "N/A")
    overall_status = row.get("Overall Status", "N/A")
    model = row.get("Model", "N/A")
    serial_number = row.get("Serial Number", "N/A")
    os_version = row.get("OS Information", row.get("OS Version", "N/A"))
    date = row.get("Date", "N/A")

    st.divider()
    st.subheader("Summary")

    col1, col2, col3 = st.columns(3)
    col1.metric("Hostname", hostname)
    col2.metric("Overall Status", overall_status)
    col3.metric("Model", model)

    col4, col5, col6 = st.columns(3)
    col4.metric("Serial Number", serial_number)
    col5.metric("OS Version", os_version)
    col6.metric("Date", date)

    st.divider()
    st.subheader("Detected PM Status")
    st.dataframe([row], use_container_width=True)

    st.divider()
    st.subheader("Download Generated Reports")

    if pdf_path.exists():
        st.download_button(
            label="Download PDF PM Report",
            data=pdf_path.read_bytes(),
            file_name=pdf_path.name,
            mime="application/pdf",
            use_container_width=True,
            type="primary",
        )
    else:
        st.warning(f"File not found: {pdf_path.name}")

    col_a, col_b = st.columns(2)

    with col_a:
        download_file(checklist_path, "Download Markdown Checklist", "text/markdown")
        download_file(findings_path, "Download JSON Findings", "application/json")
        download_file(explanation_path, "Download Explanation Report", "text/markdown")

    with col_b:
        download_file(dashboard_path, "Download HTML Dashboard", "text/html")
        download_file(index_dashboard_path, "Download Index Dashboard", "text/html")
        download_file(summary_csv_path, "Download CSV Summary", "text/csv")


st.set_page_config(
    page_title="Solaris PM Analyzer",
    page_icon="🖥️",
    layout="wide",
)

st.title("Solaris PM Automation")
st.subheader("Preventive Maintenance Report Analyzer")

st.write(
    "Upload a Solaris PM `.txt` report generated by `Solaris_PM.sh` "
    "or paste the raw PM output directly. "
    "The tool will analyze the report and generate checklist, findings, explanation, dashboard, CSV, and PDF outputs."
)

st.warning(
    "Public demo mode: use the sample report or sanitized PM output only. "
    "Do not upload real customer PM data, server serial numbers, or production logs."
)

uploaded_file = st.file_uploader(
    "Upload Solaris PM TXT report",
    type=["txt"],
)

pasted_text = st.text_area(
    "Paste Solaris PM TXT output",
    height=300,
    placeholder="Paste raw Solaris PM report output here...",
)

action_col, sample_col = st.columns([2, 1])
generate_clicked = action_col.button("Generate PM Report", use_container_width=True)
sample_clicked = sample_col.button("Try Sample Report", use_container_width=True)

if generate_clicked or sample_clicked:
    input_path = None
    run_output_dir = None
    upload_dir, run_output_dir, timestamp = prepare_run_folders()

    if sample_clicked:
        if SAMPLE_REPORT.exists():
            input_path = SAMPLE_REPORT
            st.success("Using the safe bundled sample report.")
        else:
            st.error(f"Sample report not found: {SAMPLE_REPORT}")
    elif uploaded_file is not None:
        safe_filename = Path(uploaded_file.name).name
        input_path = upload_dir / f"{timestamp}_{safe_filename}"
        input_path.write_bytes(uploaded_file.getvalue())
        st.success(f"Using uploaded file: {safe_filename}")
    elif pasted_text and pasted_text.strip():
        input_path = upload_dir / f"manual_pm_report_{timestamp}.txt"
        input_path.write_text(pasted_text, encoding="utf-8")
        st.success(f"Pasted text saved to: {input_path.name}")
    else:
        st.warning("Please upload a Solaris PM .txt file, paste PM report text, or try the sample report.")

    if input_path is not None:
        try:
            with st.spinner("Analyzing Solaris PM report..."):
                row = process_file(input_path, output_dir=run_output_dir)
                write_summary_csv([row], output_dir=run_output_dir)
                write_index_dashboard([row], output_dir=run_output_dir)

            st.session_state.last_result = {
                "row": row,
                "input_name": input_path.stem,
                "output_dir": str(run_output_dir),
            }
            st.success("Analysis completed.")

        except Exception as e:
            st.error(f"Analysis failed: {e}")

if "last_result" in st.session_state:
    render_result(st.session_state.last_result)
