from pathlib import Path

import streamlit as st

from src.solaris_pm import process_file, write_index_dashboard, write_summary_csv


OUTPUT_DIR = Path("outputs")
UPLOAD_DIR = Path("web_uploads")


def download_file(file_path, label, mime_type):
    if file_path.exists():
        st.download_button(
            label=label,
            data=file_path.read_bytes(),
            file_name=file_path.name,
            mime=mime_type,
            use_container_width=True,
        )
    else:
        st.warning(f"File not found: {file_path.name}")


st.set_page_config(
    page_title="Solaris PM Analyzer",
    page_icon="🖥️",
    layout="wide",
)

st.title("Solaris PM Automation")
st.subheader("Preventive Maintenance Report Analyzer")

st.write(
    "Upload a Solaris PM `.txt` report generated by `Solaris_PM.sh`. "
    "The tool will analyze the report and generate checklist, findings, explanation, dashboard, CSV, and PDF outputs."
)

uploaded_file = st.file_uploader(
    "Upload Solaris PM TXT report",
    type=["txt"],
)

if uploaded_file is not None:
    UPLOAD_DIR.mkdir(exist_ok=True)
    OUTPUT_DIR.mkdir(exist_ok=True)

    safe_filename = Path(uploaded_file.name).name
    input_path = UPLOAD_DIR / safe_filename

    input_path.write_bytes(uploaded_file.getvalue())

    st.success(f"Uploaded file: {safe_filename}")

    if st.button("Analyze PM Report", use_container_width=True):
        with st.spinner("Analyzing Solaris PM report..."):
            row = process_file(input_path)

            # Generate single-file summary outputs for Streamlit download
            write_summary_csv([row])
            write_index_dashboard([row])

        st.success("Analysis completed.")

        input_name = input_path.stem

        checklist_path = OUTPUT_DIR / f"{input_name}_checklist.md"
        findings_path = OUTPUT_DIR / f"{input_name}_findings.json"
        explanation_path = OUTPUT_DIR / f"{input_name}_explanation.md"
        dashboard_path = OUTPUT_DIR / f"{input_name}_dashboard.html"
        pdf_path = OUTPUT_DIR / f"{input_name}_pm_report.pdf"
        summary_csv_path = OUTPUT_DIR / "summary.csv"
        index_dashboard_path = OUTPUT_DIR / "index.html"

        hostname = row.get("Hostname", "N/A")
        overall_status = row.get("Overall Status", "N/A")
        model = row.get("Model", "N/A")
        serial_number = row.get("Serial Number", "N/A")

        st.divider()

        col1, col2, col3, col4 = st.columns(4)

        col1.metric("Hostname", hostname)
        col2.metric("Overall Status", overall_status)
        col3.metric("Model", model)
        col4.metric("Serial Number", serial_number)

        st.divider()

        st.subheader("Detected PM Status")

        st.dataframe(
            [row],
            use_container_width=True,
        )

        st.divider()

        st.subheader("Download Generated Reports")

        col_a, col_b, col_c = st.columns(3)

        with col_a:
            download_file(
                checklist_path,
                "Download Markdown Checklist",
                "text/markdown",
            )

            download_file(
                findings_path,
                "Download JSON Findings",
                "application/json",
            )

            download_file(
                explanation_path,
                "Download Explanation Report",
                "text/markdown",
            )

        with col_b:
            download_file(
                dashboard_path,
                "Download Server HTML Dashboard",
                "text/html",
            )

            download_file(
                index_dashboard_path,
                "Download Index HTML Dashboard",
                "text/html",
            )

            download_file(
                summary_csv_path,
                "Download CSV Summary",
                "text/csv",
            )

        with col_c:
            download_file(
                pdf_path,
                "Download PDF PM Report",
                "application/pdf",
            )

        st.info("Real customer PM files are saved locally only. Do not commit files from `web_uploads/` or `outputs/`.")
else:
    st.info("Upload a Solaris PM `.txt` file to begin.")